server:
  port: 5000

jwt:
  TOKEN_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: MYSQL


